# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0609c5e61ad25731d9de4f71f0a3ed6f45f0c7893129a255116bee3107c134fbc4aca114f9d6a72db7ccee64c2372749621b835925ac9be562968836d59695f7

test:
  secret_key_base: cf85e5013953b25ae9ce43d207e457096496d7a8961d42edd7473ce2b81f86a740ed1f3dd9ea87b6f821d5b2d8d5e4e32cdccebd2d9fba9b878acd10c9b3a632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
